---
- name: "Create VPC"
  hosts: localhost
  gather_facts: no

  tasks:
    - name: create vpc
      local_action:
        module: ec2_vpc
        state: present
        cidr_block: "{{ vpc_cidr }}"
        resource_tags: { "Name":"Public VPC {{ region }}" }
        subnets:

          #
          # ELB subnets
          #
          - cidr: "{{ elb_cidr_1 }}"
            az: "{{ region }}{{ az_1 }}"
            resource_tags: { "Name": "ELB CIDR {{ region }}{{ az_1 }}" }
          - cidr: "{{ elb_cidr_2 }}"
            az: "{{ region }}{{ az_2 }}"
            resource_tags: { "Name": "ELB CIDR {{ region }}{{ az_2 }}" }
          - cidr: "{{ elb_cidr_3 }}"
            az: "{{ region }}{{ az_3 }}"
            resource_tags: { "Name": "ELB CIDR {{ region }}{{ az_3 }}" }

          #
          # EC2 subnets
          #
          - cidr: "{{ ec2_cidr_1 }}"
            az: "{{ region }}{{ az_1 }}"
            resource_tags: { "Name": "EC2 CIDR {{ region }}{{ az_1 }}" }
          - cidr: "{{ ec2_cidr_2 }}"
            az: "{{ region }}{{ az_2 }}"
            resource_tags: { "Name": "EC2 CIDR {{ region }}{{ az_2 }}" }
          - cidr: "{{ ec2_cidr_3 }}"
            az: "{{ region }}{{ az_3 }}"
            resource_tags: { "Name": "EC2 CIDR {{ region }}{{ az_3 }}" }

        internet_gateway: True
        route_tables:
          - subnets:
              - "{{ ec2_cidr_1 }}"
              - "{{ ec2_cidr_2 }}"
              - "{{ ec2_cidr_3 }}"
            routes:
              - dest: 0.0.0.0/0
                gw: igw

        region: "{{ region }}"
      register: vpc
